### ISSUE TITLE
¿Por qué hay modificaciones en este fichero si no se trabajó con ellos durante la clase?

### ISSUE THREAD

**Issue by frodriSanDocente** [meel06/PHP-practic-SKILLS_UP#5]
https://github.com/meel06/PHP-practic-SKILLS_UP/blob/72ef1c04afd522c20062f84daa841d5f82ed2bf2/public/index.html#L92

El código modificado no tiene sentido, no se tocó durante la clase ni tenías ningún issue abierto sobre esas partes modificadas. Vuelve a dejarlo como estaba anteriormente.

**Comment by meel06** [comment]
Ya modifiqué los name de los inputs.
