### ISSUE TITLE
Después de limpiar los datos, deberían estar la validaciones de los tres datos requeridos.

### ISSUE THREAD

**Issue by frodriSanDocente** [meel06/PHP-practic-SKILLS_UP#7]
https://github.com/meel06/PHP-practic-SKILLS_UP/blob/72ef1c04afd522c20062f84daa841d5f82ed2bf2/modules/include/news_reg.php#L54

Te falta añadir las validaciones hechas con los tres datos requeridos. Se ha hecho en clase y se ha revisado. Revisa los repositorios de los compañeros de las 2 primeras fila o la tuya, para que observes las diferencias. 

**Se repasará en clase esos errores.**

**Comment by meel06** [comment]
Ya lo hice, fijándome en el repositorio de un compañero.
